import Head from "next/head";
import { type NextPage } from "next";


const SinglePostPage: NextPage = () => {

  
  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div>Post View</div>
      </main>
    </>
  );
};

export default SinglePostPage;
